CREATE TABLE PRODUCT(PRODUCT_ID VARCHAR(255) PRIMARY KEY, 
   NAME VARCHAR(255),
   UNIT_PRICE DECIMAL(20, 2),
   DESCRIPTION VARCHAR(255),
   MANUFACTURER VARCHAR(255),
   CATEGORY VARCHAR(255),
   UNITS_IN_STOCK BIGINT,
   UNITS_IN_ORDER BIGINT,
   DISCONTINUED BOOLEAN,
   CONDITION VARCHAR(255));
   
CREATE TABLE CART(CART_ID VARCHAR(255) PRIMARY KEY,
	GRAND_TOTAL DECIMAL(20, 0));
	
CREATE TABLE CART_ITEM( CART_ITEM_ID INT auto_increment PRIMARY KEY,
	CART_ID VARCHAR(255) NOT NULL,
	PRODUCT_ID VARCHAR(255) NOT NULL,
	QUANTITY BIGINT,
	TOTAL_PRICE DECIMAL(20, 2));

ALTER TABLE CART_ITEM
    ADD FOREIGN KEY (CART_ID) 
    REFERENCES CART(CART_ID);
    
ALTER TABLE CART_ITEM
    ADD FOREIGN KEY (PRODUCT_ID) 
    REFERENCES PRODUCT(PRODUCT_ID);
    
CREATE TABLE ADDRESS( ADDRESS_ID INT auto_increment PRIMARY KEY,
	DOOR_NO VARCHAR(255),
	STREET_NAME VARCHAR(255),
	AREA_NAME VARCHAR(255),
	STATE VARCHAR(255),
	COUNTRY VARCHAR(255),
	ZIP_CODE VARCHAR(255));
	
CREATE TABLE SHIPPING_DETAIL( SHIPPING_DETAIL_ID INT auto_increment PRIMARY KEY,
	NAME VARCHAR(255),
	STREET_NAME VARCHAR(255),
	SHIPPING_DATE DATE,
	ADDRESS_ID INT);
	
ALTER TABLE SHIPPING_DETAIL
    ADD FOREIGN KEY (ADDRESS_ID) 
    REFERENCES ADDRESS(ADDRESS_ID);
    
CREATE TABLE CUSTOMER( CUSTOMER_ID VARCHAR(255) PRIMARY KEY,
	NAME VARCHAR(255),
	ADDRESS_ID INT,
	PHONE_NUMBER VARCHAR(255));
	
ALTER TABLE CUSTOMER
    ADD FOREIGN KEY (ADDRESS_ID) 
    REFERENCES ADDRESS(ADDRESS_ID);
    
CREATE TABLE ORDER_CONFIRMATION( ORDER_ID INT auto_increment PRIMARY KEY,
	CART_ID VARCHAR(255) NOT NULL,
	CUSTOMER_ID VARCHAR(255) NOT NULL,
	SHIPPING_DETAIL_ID INT NOT NULL);
	
ALTER TABLE ORDER_CONFIRMATION
    ADD FOREIGN KEY (CART_ID) 
    REFERENCES CART(CART_ID);
    
ALTER TABLE ORDER_CONFIRMATION
    ADD FOREIGN KEY (CUSTOMER_ID) 
    REFERENCES CUSTOMER(CUSTOMER_ID);
    
ALTER TABLE ORDER_CONFIRMATION
    ADD FOREIGN KEY (SHIPPING_DETAIL_ID) 
    REFERENCES SHIPPING_DETAIL(SHIPPING_DETAIL_ID);
    
    