CREATE TABLE PRODUCT(PRODUCT_ID VARCHAR(255) PRIMARY KEY, 
   NAME VARCHAR(255),
   UNIT_PRICE DECIMAL(20, 2),
   DESCRIPTION VARCHAR(255),
   MANUFACTURER VARCHAR(255),
   CATEGORY VARCHAR(255),
   UNITS_IN_STOCK BIGINT,
   UNITS_IN_ORDER BIGINT,
   DISCONTINUED BOOLEAN,
   CONDITION VARCHAR(255));
   
CREATE TABLE CART(CART_ID VARCHAR(255) PRIMARY KEY,
	GRAND_TOTAL DECIMAL(20, 0));
	
CREATE TABLE CART_ITEM( CART_ITEM_ID INT auto_increment PRIMARY KEY,
	CART_ID VARCHAR(255) NOT NULL,
	PRODUCT_ID VARCHAR(255) NOT NULL,
	QUANTITY BIGINT,
	TOTAL_PRICE DECIMAL(20, 2));

ALTER TABLE CART_ITEM
    ADD FOREIGN KEY (CART_ID) 
    REFERENCES CART(CART_ID);
    
ALTER TABLE CART_ITEM
    ADD FOREIGN KEY (PRODUCT_ID) 
    REFERENCES PRODUCT(PRODUCT_ID);